// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/terminal/CANBUSData/Report/EngineLiquidLevel.proto

package com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report;

public final class LCEngineLiquidLevel {
  private LCEngineLiquidLevel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EngineLiquidLevelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 fuelPressure = 1;
    boolean hasFuelPressure();
    int getFuelPressure();
    
    // optional float engineOilLevel = 2;
    boolean hasEngineOilLevel();
    float getEngineOilLevel();
    
    // optional int32 engineOilPressure = 3;
    boolean hasEngineOilPressure();
    int getEngineOilPressure();
    
    // optional float engineCoolantLevel = 4;
    boolean hasEngineCoolantLevel();
    float getEngineCoolantLevel();
  }
  public static final class EngineLiquidLevel extends
      com.google.protobuf.GeneratedMessage
      implements EngineLiquidLevelOrBuilder {
    // Use EngineLiquidLevel.newBuilder() to construct.
    private EngineLiquidLevel(Builder builder) {
      super(builder);
    }
    private EngineLiquidLevel(boolean noInit) {}
    
    private static final EngineLiquidLevel defaultInstance;
    public static EngineLiquidLevel getDefaultInstance() {
      return defaultInstance;
    }
    
    public EngineLiquidLevel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.internal_static_EngineLiquidLevel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.internal_static_EngineLiquidLevel_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 fuelPressure = 1;
    public static final int FUELPRESSURE_FIELD_NUMBER = 1;
    private int fuelPressure_;
    public boolean hasFuelPressure() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getFuelPressure() {
      return fuelPressure_;
    }
    
    // optional float engineOilLevel = 2;
    public static final int ENGINEOILLEVEL_FIELD_NUMBER = 2;
    private float engineOilLevel_;
    public boolean hasEngineOilLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getEngineOilLevel() {
      return engineOilLevel_;
    }
    
    // optional int32 engineOilPressure = 3;
    public static final int ENGINEOILPRESSURE_FIELD_NUMBER = 3;
    private int engineOilPressure_;
    public boolean hasEngineOilPressure() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getEngineOilPressure() {
      return engineOilPressure_;
    }
    
    // optional float engineCoolantLevel = 4;
    public static final int ENGINECOOLANTLEVEL_FIELD_NUMBER = 4;
    private float engineCoolantLevel_;
    public boolean hasEngineCoolantLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getEngineCoolantLevel() {
      return engineCoolantLevel_;
    }
    
    private void initFields() {
      fuelPressure_ = 0;
      engineOilLevel_ = 0F;
      engineOilPressure_ = 0;
      engineCoolantLevel_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fuelPressure_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, engineOilLevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, engineOilPressure_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, engineCoolantLevel_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fuelPressure_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, engineOilLevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, engineOilPressure_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, engineCoolantLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.internal_static_EngineLiquidLevel_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.internal_static_EngineLiquidLevel_fieldAccessorTable;
      }
      
      // Construct using com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fuelPressure_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        engineOilLevel_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        engineOilPressure_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        engineCoolantLevel_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel.getDescriptor();
      }
      
      public com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel getDefaultInstanceForType() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel.getDefaultInstance();
      }
      
      public com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel build() {
        com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel buildPartial() {
        com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel result = new com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fuelPressure_ = fuelPressure_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.engineOilLevel_ = engineOilLevel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.engineOilPressure_ = engineOilPressure_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.engineCoolantLevel_ = engineCoolantLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel) {
          return mergeFrom((com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel other) {
        if (other == com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel.getDefaultInstance()) return this;
        if (other.hasFuelPressure()) {
          setFuelPressure(other.getFuelPressure());
        }
        if (other.hasEngineOilLevel()) {
          setEngineOilLevel(other.getEngineOilLevel());
        }
        if (other.hasEngineOilPressure()) {
          setEngineOilPressure(other.getEngineOilPressure());
        }
        if (other.hasEngineCoolantLevel()) {
          setEngineCoolantLevel(other.getEngineCoolantLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fuelPressure_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              engineOilLevel_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              engineOilPressure_ = input.readInt32();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              engineCoolantLevel_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 fuelPressure = 1;
      private int fuelPressure_ ;
      public boolean hasFuelPressure() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getFuelPressure() {
        return fuelPressure_;
      }
      public Builder setFuelPressure(int value) {
        bitField0_ |= 0x00000001;
        fuelPressure_ = value;
        onChanged();
        return this;
      }
      public Builder clearFuelPressure() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fuelPressure_ = 0;
        onChanged();
        return this;
      }
      
      // optional float engineOilLevel = 2;
      private float engineOilLevel_ ;
      public boolean hasEngineOilLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getEngineOilLevel() {
        return engineOilLevel_;
      }
      public Builder setEngineOilLevel(float value) {
        bitField0_ |= 0x00000002;
        engineOilLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearEngineOilLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        engineOilLevel_ = 0F;
        onChanged();
        return this;
      }
      
      // optional int32 engineOilPressure = 3;
      private int engineOilPressure_ ;
      public boolean hasEngineOilPressure() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getEngineOilPressure() {
        return engineOilPressure_;
      }
      public Builder setEngineOilPressure(int value) {
        bitField0_ |= 0x00000004;
        engineOilPressure_ = value;
        onChanged();
        return this;
      }
      public Builder clearEngineOilPressure() {
        bitField0_ = (bitField0_ & ~0x00000004);
        engineOilPressure_ = 0;
        onChanged();
        return this;
      }
      
      // optional float engineCoolantLevel = 4;
      private float engineCoolantLevel_ ;
      public boolean hasEngineCoolantLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getEngineCoolantLevel() {
        return engineCoolantLevel_;
      }
      public Builder setEngineCoolantLevel(float value) {
        bitField0_ |= 0x00000008;
        engineCoolantLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearEngineCoolantLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        engineCoolantLevel_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EngineLiquidLevel)
    }
    
    static {
      defaultInstance = new EngineLiquidLevel(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EngineLiquidLevel)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EngineLiquidLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EngineLiquidLevel_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=core/proto/terminal/CANBUSData/Report/" +
      "EngineLiquidLevel.proto\"x\n\021EngineLiquidL" +
      "evel\022\024\n\014fuelPressure\030\001 \001(\005\022\026\n\016engineOilL" +
      "evel\030\002 \001(\002\022\031\n\021engineOilPressure\030\003 \001(\005\022\032\n" +
      "\022engineCoolantLevel\030\004 \001(\002B`\nIcom.navinfo" +
      ".opentsp.platform.location.protocol.term" +
      "inal.CANBUSData.ReportB\023LCEngineLiquidLe" +
      "vel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_EngineLiquidLevel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_EngineLiquidLevel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EngineLiquidLevel_descriptor,
              new java.lang.String[] { "FuelPressure", "EngineOilLevel", "EngineOilPressure", "EngineCoolantLevel", },
              com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel.class,
              com.navinfo.opentsp.platform.location.protocol.terminal.CANBUSData.Report.LCEngineLiquidLevel.EngineLiquidLevel.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
