// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/terminal/query/travelrecorder/TRCollectMileageRes.proto

package com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder;

public final class LCTRCollectMileageRes {
  private LCTRCollectMileageRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TRCollectMileageResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 serialNumber = 1;
    boolean hasSerialNumber();
    int getSerialNumber();
    
    // required .ResponseResult result = 2;
    boolean hasResult();
    com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult getResult();
    
    // optional int64 currentDate = 3;
    boolean hasCurrentDate();
    long getCurrentDate();
    
    // optional int64 installDate = 4;
    boolean hasInstallDate();
    long getInstallDate();
    
    // optional int32 originalMileage = 5;
    boolean hasOriginalMileage();
    int getOriginalMileage();
    
    // optional int32 cumulativeMileage = 6;
    boolean hasCumulativeMileage();
    int getCumulativeMileage();
  }
  public static final class TRCollectMileageRes extends
      com.google.protobuf.GeneratedMessage
      implements TRCollectMileageResOrBuilder {
    // Use TRCollectMileageRes.newBuilder() to construct.
    private TRCollectMileageRes(Builder builder) {
      super(builder);
    }
    private TRCollectMileageRes(boolean noInit) {}
    
    private static final TRCollectMileageRes defaultInstance;
    public static TRCollectMileageRes getDefaultInstance() {
      return defaultInstance;
    }
    
    public TRCollectMileageRes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.internal_static_TRCollectMileageRes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.internal_static_TRCollectMileageRes_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 serialNumber = 1;
    public static final int SERIALNUMBER_FIELD_NUMBER = 1;
    private int serialNumber_;
    public boolean hasSerialNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSerialNumber() {
      return serialNumber_;
    }
    
    // required .ResponseResult result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult getResult() {
      return result_;
    }
    
    // optional int64 currentDate = 3;
    public static final int CURRENTDATE_FIELD_NUMBER = 3;
    private long currentDate_;
    public boolean hasCurrentDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getCurrentDate() {
      return currentDate_;
    }
    
    // optional int64 installDate = 4;
    public static final int INSTALLDATE_FIELD_NUMBER = 4;
    private long installDate_;
    public boolean hasInstallDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getInstallDate() {
      return installDate_;
    }
    
    // optional int32 originalMileage = 5;
    public static final int ORIGINALMILEAGE_FIELD_NUMBER = 5;
    private int originalMileage_;
    public boolean hasOriginalMileage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getOriginalMileage() {
      return originalMileage_;
    }
    
    // optional int32 cumulativeMileage = 6;
    public static final int CUMULATIVEMILEAGE_FIELD_NUMBER = 6;
    private int cumulativeMileage_;
    public boolean hasCumulativeMileage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCumulativeMileage() {
      return cumulativeMileage_;
    }
    
    private void initFields() {
      serialNumber_ = 0;
      result_ = com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult.success;
      currentDate_ = 0L;
      installDate_ = 0L;
      originalMileage_ = 0;
      cumulativeMileage_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSerialNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serialNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, result_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, currentDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, installDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, originalMileage_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, cumulativeMileage_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serialNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, result_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, currentDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, installDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, originalMileage_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, cumulativeMileage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.internal_static_TRCollectMileageRes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.internal_static_TRCollectMileageRes_fieldAccessorTable;
      }
      
      // Construct using com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serialNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult.success;
        bitField0_ = (bitField0_ & ~0x00000002);
        currentDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        installDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        originalMileage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        cumulativeMileage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes.getDescriptor();
      }
      
      public com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes getDefaultInstanceForType() {
        return com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes.getDefaultInstance();
      }
      
      public com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes build() {
        com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes buildPartial() {
        com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes result = new com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialNumber_ = serialNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currentDate_ = currentDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.installDate_ = installDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.originalMileage_ = originalMileage_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.cumulativeMileage_ = cumulativeMileage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes) {
          return mergeFrom((com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes other) {
        if (other == com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes.getDefaultInstance()) return this;
        if (other.hasSerialNumber()) {
          setSerialNumber(other.getSerialNumber());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasCurrentDate()) {
          setCurrentDate(other.getCurrentDate());
        }
        if (other.hasInstallDate()) {
          setInstallDate(other.getInstallDate());
        }
        if (other.hasOriginalMileage()) {
          setOriginalMileage(other.getOriginalMileage());
        }
        if (other.hasCumulativeMileage()) {
          setCumulativeMileage(other.getCumulativeMileage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSerialNumber()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serialNumber_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult value = com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                result_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              currentDate_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              installDate_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              originalMileage_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              cumulativeMileage_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 serialNumber = 1;
      private int serialNumber_ ;
      public boolean hasSerialNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSerialNumber() {
        return serialNumber_;
      }
      public Builder setSerialNumber(int value) {
        bitField0_ |= 0x00000001;
        serialNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearSerialNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNumber_ = 0;
        onChanged();
        return this;
      }
      
      // required .ResponseResult result = 2;
      private com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult result_ = com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult.success;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult getResult() {
        return result_;
      }
      public Builder setResult(com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.ResponseResult.success;
        onChanged();
        return this;
      }
      
      // optional int64 currentDate = 3;
      private long currentDate_ ;
      public boolean hasCurrentDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getCurrentDate() {
        return currentDate_;
      }
      public Builder setCurrentDate(long value) {
        bitField0_ |= 0x00000004;
        currentDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 installDate = 4;
      private long installDate_ ;
      public boolean hasInstallDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getInstallDate() {
        return installDate_;
      }
      public Builder setInstallDate(long value) {
        bitField0_ |= 0x00000008;
        installDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearInstallDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        installDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 originalMileage = 5;
      private int originalMileage_ ;
      public boolean hasOriginalMileage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getOriginalMileage() {
        return originalMileage_;
      }
      public Builder setOriginalMileage(int value) {
        bitField0_ |= 0x00000010;
        originalMileage_ = value;
        onChanged();
        return this;
      }
      public Builder clearOriginalMileage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        originalMileage_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 cumulativeMileage = 6;
      private int cumulativeMileage_ ;
      public boolean hasCumulativeMileage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCumulativeMileage() {
        return cumulativeMileage_;
      }
      public Builder setCumulativeMileage(int value) {
        bitField0_ |= 0x00000020;
        cumulativeMileage_ = value;
        onChanged();
        return this;
      }
      public Builder clearCumulativeMileage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cumulativeMileage_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:TRCollectMileageRes)
    }
    
    static {
      defaultInstance = new TRCollectMileageRes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TRCollectMileageRes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TRCollectMileageRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TRCollectMileageRes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBcore/proto/terminal/query/travelrecord" +
      "er/TRCollectMileageRes.proto\032+core/proto" +
      "/common/java/ResponseResult.proto\"\252\001\n\023TR" +
      "CollectMileageRes\022\024\n\014serialNumber\030\001 \002(\005\022" +
      "\037\n\006result\030\002 \002(\0162\017.ResponseResult\022\023\n\013curr" +
      "entDate\030\003 \001(\003\022\023\n\013installDate\030\004 \001(\003\022\027\n\017or" +
      "iginalMileage\030\005 \001(\005\022\031\n\021cumulativeMileage" +
      "\030\006 \001(\005Be\nLcom.navinfo.opentsp.platform.l" +
      "ocation.protocol.terminal.query.travelre" +
      "corderB\025LCTRCollectMileageRes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TRCollectMileageRes_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TRCollectMileageRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TRCollectMileageRes_descriptor,
              new java.lang.String[] { "SerialNumber", "Result", "CurrentDate", "InstallDate", "OriginalMileage", "CumulativeMileage", },
              com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes.class,
              com.navinfo.opentsp.platform.location.protocol.terminal.query.travelrecorder.LCTRCollectMileageRes.TRCollectMileageRes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.navinfo.opentsp.platform.location.protocol.common.LCResponseResult.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
