// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/terminal/setting/java/QueryAppointPara.proto

package com.navinfo.opentsp.platform.location.protocol.terminal.setting;

public final class LCQueryAppointPara {
  private LCQueryAppointPara() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QueryAppointParaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ParameterMessageNumber numbers = 1;
    java.util.List<com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber> getNumbersList();
    int getNumbersCount();
    com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber getNumbers(int index);
  }
  public static final class QueryAppointPara extends
      com.google.protobuf.GeneratedMessage
      implements QueryAppointParaOrBuilder {
    // Use QueryAppointPara.newBuilder() to construct.
    private QueryAppointPara(Builder builder) {
      super(builder);
    }
    private QueryAppointPara(boolean noInit) {}
    
    private static final QueryAppointPara defaultInstance;
    public static QueryAppointPara getDefaultInstance() {
      return defaultInstance;
    }
    
    public QueryAppointPara getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LCQueryAppointPara.internal_static_QueryAppointPara_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LCQueryAppointPara.internal_static_QueryAppointPara_fieldAccessorTable;
    }
    
    // repeated .ParameterMessageNumber numbers = 1;
    public static final int NUMBERS_FIELD_NUMBER = 1;
    private java.util.List<com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber> numbers_;
    public java.util.List<com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber> getNumbersList() {
      return numbers_;
    }
    public int getNumbersCount() {
      return numbers_.size();
    }
    public com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber getNumbers(int index) {
      return numbers_.get(index);
    }
    
    private void initFields() {
      numbers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < numbers_.size(); i++) {
        output.writeEnum(1, numbers_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < numbers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(numbers_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * numbers_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static QueryAppointPara parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static QueryAppointPara parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static QueryAppointPara parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static QueryAppointPara parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static QueryAppointPara parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static QueryAppointPara parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static QueryAppointPara parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static QueryAppointPara parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static QueryAppointPara parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static QueryAppointPara parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QueryAppointPara prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QueryAppointParaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LCQueryAppointPara.internal_static_QueryAppointPara_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LCQueryAppointPara.internal_static_QueryAppointPara_fieldAccessorTable;
      }
      
      // Construct using com.navinfo.opentsp.platform.location.protocol.terminal.setting.LCQueryAppointPara.QueryAppointPara.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        numbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryAppointPara.getDescriptor();
      }
      
      public QueryAppointPara getDefaultInstanceForType() {
        return QueryAppointPara.getDefaultInstance();
      }
      
      public QueryAppointPara build() {
        QueryAppointPara result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private QueryAppointPara buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        QueryAppointPara result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public QueryAppointPara buildPartial() {
        QueryAppointPara result = new QueryAppointPara(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          numbers_ = java.util.Collections.unmodifiableList(numbers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.numbers_ = numbers_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryAppointPara) {
          return mergeFrom((QueryAppointPara)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(QueryAppointPara other) {
        if (other == QueryAppointPara.getDefaultInstance()) return this;
        if (!other.numbers_.isEmpty()) {
          if (numbers_.isEmpty()) {
            numbers_ = other.numbers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNumbersIsMutable();
            numbers_.addAll(other.numbers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber value = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                addNumbers(value);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber value = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  addNumbers(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ParameterMessageNumber numbers = 1;
      private java.util.List<com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber> numbers_ =
        java.util.Collections.emptyList();
      private void ensureNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          numbers_ = new java.util.ArrayList<com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber>(numbers_);
          bitField0_ |= 0x00000001;
        }
      }
      public java.util.List<com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber> getNumbersList() {
        return java.util.Collections.unmodifiableList(numbers_);
      }
      public int getNumbersCount() {
        return numbers_.size();
      }
      public com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber getNumbers(int index) {
        return numbers_.get(index);
      }
      public Builder setNumbers(
          int index, com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNumbersIsMutable();
        numbers_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addNumbers(com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNumbersIsMutable();
        numbers_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllNumbers(
          Iterable<? extends com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.ParameterMessageNumber> values) {
        ensureNumbersIsMutable();
        super.addAll(values, numbers_);
        onChanged();
        return this;
      }
      public Builder clearNumbers() {
        numbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:QueryAppointPara)
    }
    
    static {
      defaultInstance = new QueryAppointPara(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:QueryAppointPara)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryAppointPara_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryAppointPara_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n7core/proto/terminal/setting/java/Query" +
      "AppointPara.proto\032<core/proto/terminal/c" +
      "ommon/java/ParameterMessageNumber.proto\"" +
      "<\n\020QueryAppointPara\022(\n\007numbers\030\001 \003(\0162\027.P" +
      "arameterMessageNumberBU\n?com.navinfo.ope" +
      "ntsp.platform.location.protocol.terminal" +
      ".settingB\022LCQueryAppointPara"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_QueryAppointPara_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_QueryAppointPara_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_QueryAppointPara_descriptor,
              new String[] { "Numbers", },
              QueryAppointPara.class,
              QueryAppointPara.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.navinfo.opentsp.platform.location.protocol.terminal.common.LCParameterMessageNumber.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
