// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/nodecluster/common/java/NodeInfo.proto

package com.navinfo.opentsp.platform.location.protocol.nodecluster.common;

public final class LCNodeInfo {
  private LCNodeInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NodeInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .NodeType types = 1;
    boolean hasTypes();
    com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType getTypes();
    
    // required bool isRedundancy = 2;
    boolean hasIsRedundancy();
    boolean getIsRedundancy();
    
    // required int64 nodeCode = 3;
    boolean hasNodeCode();
    long getNodeCode();
    
    // required string addressLocalIP = 4;
    boolean hasAddressLocalIP();
    String getAddressLocalIP();
    
    // optional string addressInternetIP = 5;
    boolean hasAddressInternetIP();
    String getAddressInternetIP();
    
    // required .DistrictCode districtCode = 6;
    boolean hasDistrictCode();
    com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode getDistrictCode();
    
    // optional int32 maxLimit = 7;
    boolean hasMaxLimit();
    int getMaxLimit();
    
    // optional int32 minLimit = 8;
    boolean hasMinLimit();
    int getMinLimit();
    
    // optional .ExtendConfig extendConfigs = 9;
    boolean hasExtendConfigs();
    com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig getExtendConfigs();
    com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfigOrBuilder getExtendConfigsOrBuilder();
  }
  public static final class NodeInfo extends
      com.google.protobuf.GeneratedMessage
      implements NodeInfoOrBuilder {
    // Use NodeInfo.newBuilder() to construct.
    private NodeInfo(Builder builder) {
      super(builder);
    }
    private NodeInfo(boolean noInit) {}
    
    private static final NodeInfo defaultInstance;
    public static NodeInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public NodeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.internal_static_NodeInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.internal_static_NodeInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .NodeType types = 1;
    public static final int TYPES_FIELD_NUMBER = 1;
    private com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType types_;
    public boolean hasTypes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType getTypes() {
      return types_;
    }
    
    // required bool isRedundancy = 2;
    public static final int ISREDUNDANCY_FIELD_NUMBER = 2;
    private boolean isRedundancy_;
    public boolean hasIsRedundancy() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsRedundancy() {
      return isRedundancy_;
    }
    
    // required int64 nodeCode = 3;
    public static final int NODECODE_FIELD_NUMBER = 3;
    private long nodeCode_;
    public boolean hasNodeCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getNodeCode() {
      return nodeCode_;
    }
    
    // required string addressLocalIP = 4;
    public static final int ADDRESSLOCALIP_FIELD_NUMBER = 4;
    private java.lang.Object addressLocalIP_;
    public boolean hasAddressLocalIP() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAddressLocalIP() {
      java.lang.Object ref = addressLocalIP_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          addressLocalIP_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressLocalIPBytes() {
      java.lang.Object ref = addressLocalIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        addressLocalIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string addressInternetIP = 5;
    public static final int ADDRESSINTERNETIP_FIELD_NUMBER = 5;
    private java.lang.Object addressInternetIP_;
    public boolean hasAddressInternetIP() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getAddressInternetIP() {
      java.lang.Object ref = addressInternetIP_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          addressInternetIP_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAddressInternetIPBytes() {
      java.lang.Object ref = addressInternetIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        addressInternetIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .DistrictCode districtCode = 6;
    public static final int DISTRICTCODE_FIELD_NUMBER = 6;
    private com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode districtCode_;
    public boolean hasDistrictCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode getDistrictCode() {
      return districtCode_;
    }
    
    // optional int32 maxLimit = 7;
    public static final int MAXLIMIT_FIELD_NUMBER = 7;
    private int maxLimit_;
    public boolean hasMaxLimit() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getMaxLimit() {
      return maxLimit_;
    }
    
    // optional int32 minLimit = 8;
    public static final int MINLIMIT_FIELD_NUMBER = 8;
    private int minLimit_;
    public boolean hasMinLimit() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getMinLimit() {
      return minLimit_;
    }
    
    // optional .ExtendConfig extendConfigs = 9;
    public static final int EXTENDCONFIGS_FIELD_NUMBER = 9;
    private com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig extendConfigs_;
    public boolean hasExtendConfigs() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig getExtendConfigs() {
      return extendConfigs_;
    }
    public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfigOrBuilder getExtendConfigsOrBuilder() {
      return extendConfigs_;
    }
    
    private void initFields() {
      types_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType.ta;
      isRedundancy_ = false;
      nodeCode_ = 0L;
      addressLocalIP_ = "";
      addressInternetIP_ = "";
      districtCode_ = com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode.none;
      maxLimit_ = 0;
      minLimit_ = 0;
      extendConfigs_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTypes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsRedundancy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddressLocalIP()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistrictCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasExtendConfigs()) {
        if (!getExtendConfigs().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, types_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isRedundancy_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, nodeCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAddressLocalIPBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAddressInternetIPBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, districtCode_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, maxLimit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, minLimit_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, extendConfigs_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, types_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isRedundancy_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, nodeCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAddressLocalIPBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAddressInternetIPBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, districtCode_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, maxLimit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, minLimit_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, extendConfigs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.internal_static_NodeInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.internal_static_NodeInfo_fieldAccessorTable;
      }
      
      // Construct using com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExtendConfigsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        types_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType.ta;
        bitField0_ = (bitField0_ & ~0x00000001);
        isRedundancy_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        addressLocalIP_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        addressInternetIP_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        districtCode_ = com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode.none;
        bitField0_ = (bitField0_ & ~0x00000020);
        maxLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        minLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (extendConfigsBuilder_ == null) {
          extendConfigs_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.getDefaultInstance();
        } else {
          extendConfigsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo.getDescriptor();
      }
      
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo getDefaultInstanceForType() {
        return com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo.getDefaultInstance();
      }
      
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo build() {
        com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo buildPartial() {
        com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo result = new com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.types_ = types_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isRedundancy_ = isRedundancy_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nodeCode_ = nodeCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.addressLocalIP_ = addressLocalIP_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.addressInternetIP_ = addressInternetIP_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.districtCode_ = districtCode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.maxLimit_ = maxLimit_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.minLimit_ = minLimit_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (extendConfigsBuilder_ == null) {
          result.extendConfigs_ = extendConfigs_;
        } else {
          result.extendConfigs_ = extendConfigsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo) {
          return mergeFrom((com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo other) {
        if (other == com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo.getDefaultInstance()) return this;
        if (other.hasTypes()) {
          setTypes(other.getTypes());
        }
        if (other.hasIsRedundancy()) {
          setIsRedundancy(other.getIsRedundancy());
        }
        if (other.hasNodeCode()) {
          setNodeCode(other.getNodeCode());
        }
        if (other.hasAddressLocalIP()) {
          setAddressLocalIP(other.getAddressLocalIP());
        }
        if (other.hasAddressInternetIP()) {
          setAddressInternetIP(other.getAddressInternetIP());
        }
        if (other.hasDistrictCode()) {
          setDistrictCode(other.getDistrictCode());
        }
        if (other.hasMaxLimit()) {
          setMaxLimit(other.getMaxLimit());
        }
        if (other.hasMinLimit()) {
          setMinLimit(other.getMinLimit());
        }
        if (other.hasExtendConfigs()) {
          mergeExtendConfigs(other.getExtendConfigs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTypes()) {
          
          return false;
        }
        if (!hasIsRedundancy()) {
          
          return false;
        }
        if (!hasNodeCode()) {
          
          return false;
        }
        if (!hasAddressLocalIP()) {
          
          return false;
        }
        if (!hasDistrictCode()) {
          
          return false;
        }
        if (hasExtendConfigs()) {
          if (!getExtendConfigs().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType value = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                types_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isRedundancy_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              nodeCode_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              addressLocalIP_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              addressInternetIP_ = input.readBytes();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode value = com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                districtCode_ = value;
              }
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              maxLimit_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              minLimit_ = input.readInt32();
              break;
            }
            case 74: {
              com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.Builder subBuilder = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.newBuilder();
              if (hasExtendConfigs()) {
                subBuilder.mergeFrom(getExtendConfigs());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setExtendConfigs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .NodeType types = 1;
      private com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType types_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType.ta;
      public boolean hasTypes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType getTypes() {
        return types_;
      }
      public Builder setTypes(com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        types_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        types_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.NodeType.ta;
        onChanged();
        return this;
      }
      
      // required bool isRedundancy = 2;
      private boolean isRedundancy_ ;
      public boolean hasIsRedundancy() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsRedundancy() {
        return isRedundancy_;
      }
      public Builder setIsRedundancy(boolean value) {
        bitField0_ |= 0x00000002;
        isRedundancy_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsRedundancy() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isRedundancy_ = false;
        onChanged();
        return this;
      }
      
      // required int64 nodeCode = 3;
      private long nodeCode_ ;
      public boolean hasNodeCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getNodeCode() {
        return nodeCode_;
      }
      public Builder setNodeCode(long value) {
        bitField0_ |= 0x00000004;
        nodeCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nodeCode_ = 0L;
        onChanged();
        return this;
      }
      
      // required string addressLocalIP = 4;
      private java.lang.Object addressLocalIP_ = "";
      public boolean hasAddressLocalIP() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAddressLocalIP() {
        java.lang.Object ref = addressLocalIP_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          addressLocalIP_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddressLocalIP(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        addressLocalIP_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddressLocalIP() {
        bitField0_ = (bitField0_ & ~0x00000008);
        addressLocalIP_ = getDefaultInstance().getAddressLocalIP();
        onChanged();
        return this;
      }
      void setAddressLocalIP(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        addressLocalIP_ = value;
        onChanged();
      }
      
      // optional string addressInternetIP = 5;
      private java.lang.Object addressInternetIP_ = "";
      public boolean hasAddressInternetIP() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getAddressInternetIP() {
        java.lang.Object ref = addressInternetIP_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          addressInternetIP_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAddressInternetIP(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        addressInternetIP_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddressInternetIP() {
        bitField0_ = (bitField0_ & ~0x00000010);
        addressInternetIP_ = getDefaultInstance().getAddressInternetIP();
        onChanged();
        return this;
      }
      void setAddressInternetIP(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        addressInternetIP_ = value;
        onChanged();
      }
      
      // required .DistrictCode districtCode = 6;
      private com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode districtCode_ = com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode.none;
      public boolean hasDistrictCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode getDistrictCode() {
        return districtCode_;
      }
      public Builder setDistrictCode(com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        districtCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearDistrictCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        districtCode_ = com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.DistrictCode.none;
        onChanged();
        return this;
      }
      
      // optional int32 maxLimit = 7;
      private int maxLimit_ ;
      public boolean hasMaxLimit() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getMaxLimit() {
        return maxLimit_;
      }
      public Builder setMaxLimit(int value) {
        bitField0_ |= 0x00000040;
        maxLimit_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxLimit() {
        bitField0_ = (bitField0_ & ~0x00000040);
        maxLimit_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 minLimit = 8;
      private int minLimit_ ;
      public boolean hasMinLimit() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getMinLimit() {
        return minLimit_;
      }
      public Builder setMinLimit(int value) {
        bitField0_ |= 0x00000080;
        minLimit_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinLimit() {
        bitField0_ = (bitField0_ & ~0x00000080);
        minLimit_ = 0;
        onChanged();
        return this;
      }
      
      // optional .ExtendConfig extendConfigs = 9;
      private com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig extendConfigs_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig, com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.Builder, com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfigOrBuilder> extendConfigsBuilder_;
      public boolean hasExtendConfigs() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig getExtendConfigs() {
        if (extendConfigsBuilder_ == null) {
          return extendConfigs_;
        } else {
          return extendConfigsBuilder_.getMessage();
        }
      }
      public Builder setExtendConfigs(com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig value) {
        if (extendConfigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          extendConfigs_ = value;
          onChanged();
        } else {
          extendConfigsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder setExtendConfigs(
          com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.Builder builderForValue) {
        if (extendConfigsBuilder_ == null) {
          extendConfigs_ = builderForValue.build();
          onChanged();
        } else {
          extendConfigsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder mergeExtendConfigs(com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig value) {
        if (extendConfigsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              extendConfigs_ != com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.getDefaultInstance()) {
            extendConfigs_ =
              com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.newBuilder(extendConfigs_).mergeFrom(value).buildPartial();
          } else {
            extendConfigs_ = value;
          }
          onChanged();
        } else {
          extendConfigsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder clearExtendConfigs() {
        if (extendConfigsBuilder_ == null) {
          extendConfigs_ = com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.getDefaultInstance();
          onChanged();
        } else {
          extendConfigsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.Builder getExtendConfigsBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getExtendConfigsFieldBuilder().getBuilder();
      }
      public com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfigOrBuilder getExtendConfigsOrBuilder() {
        if (extendConfigsBuilder_ != null) {
          return extendConfigsBuilder_.getMessageOrBuilder();
        } else {
          return extendConfigs_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig, com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.Builder, com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfigOrBuilder> 
          getExtendConfigsFieldBuilder() {
        if (extendConfigsBuilder_ == null) {
          extendConfigsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig, com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfig.Builder, com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.ExtendConfigOrBuilder>(
                  extendConfigs_,
                  getParentForChildren(),
                  isClean());
          extendConfigs_ = null;
        }
        return extendConfigsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:NodeInfo)
    }
    
    static {
      defaultInstance = new NodeInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NodeInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NodeInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1core/proto/nodecluster/common/java/Nod" +
      "eInfo.proto\032)core/proto/common/java/Dist" +
      "rictCode.proto\0321core/proto/nodecluster/c" +
      "ommon/java/NodeType.proto\0325core/proto/no" +
      "decluster/common/java/ExtendConfig.proto" +
      "\"\356\001\n\010NodeInfo\022\030\n\005types\030\001 \002(\0162\t.NodeType\022" +
      "\024\n\014isRedundancy\030\002 \002(\010\022\020\n\010nodeCode\030\003 \002(\003\022" +
      "\026\n\016addressLocalIP\030\004 \002(\t\022\031\n\021addressIntern" +
      "etIP\030\005 \001(\t\022#\n\014districtCode\030\006 \002(\0162\r.Distr" +
      "ictCode\022\020\n\010maxLimit\030\007 \001(\005\022\020\n\010minLimit\030\010 ",
      "\001(\005\022$\n\rextendConfigs\030\t \001(\0132\r.ExtendConfi" +
      "gBO\nAcom.navinfo.opentsp.platform.locati" +
      "on.protocol.nodecluster.commonB\nLCNodeIn" +
      "fo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NodeInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NodeInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NodeInfo_descriptor,
              new java.lang.String[] { "Types", "IsRedundancy", "NodeCode", "AddressLocalIP", "AddressInternetIP", "DistrictCode", "MaxLimit", "MinLimit", "ExtendConfigs", },
              com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo.class,
              com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeInfo.NodeInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.navinfo.opentsp.platform.location.protocol.common.LCDistrictCode.getDescriptor(),
          com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCNodeType.getDescriptor(),
          com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCExtendConfig.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
