// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/nodecluster/common/java/MonitorCacheSize.proto

package com.navinfo.opentsp.platform.location.protocol.nodecluster.common;

public final class LCMonitorCacheSize {
  private LCMonitorCacheSize() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MonitorCacheSizeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MonitorCacheSize.CacheType types = 1;
    boolean hasTypes();
    MonitorCacheSize.CacheType getTypes();
    
    // required int32 cacheSize = 2;
    boolean hasCacheSize();
    int getCacheSize();
  }
  public static final class MonitorCacheSize extends
      com.google.protobuf.GeneratedMessage
      implements MonitorCacheSizeOrBuilder {
    // Use MonitorCacheSize.newBuilder() to construct.
    private MonitorCacheSize(Builder builder) {
      super(builder);
    }
    private MonitorCacheSize(boolean noInit) {}
    
    private static final MonitorCacheSize defaultInstance;
    public static MonitorCacheSize getDefaultInstance() {
      return defaultInstance;
    }
    
    public MonitorCacheSize getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LCMonitorCacheSize.internal_static_MonitorCacheSize_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LCMonitorCacheSize.internal_static_MonitorCacheSize_fieldAccessorTable;
    }
    
    public enum CacheType
        implements com.google.protobuf.ProtocolMessageEnum {
      ta_packetHandle(0, 1),
      ta_messageAddressing(1, 2),
      ta_messageAnswerTimeout(2, 3),
      ta_commonCache(3, 4),
      ta_dataLocalSerialization(4, 5),
      dp_areaData(5, 32),
      dp_regularData(6, 33),
      dp_latestLocationData(7, 34),
      dp_dictData(8, 35),
      dp_commonData(9, 36),
      dp_terminalParameter(10, 37),
      dp_dpAndTaDataGuarantee(11, 38),
      dp_messageAddressing(12, 39),
      dp_encryptData(13, 40),
      dsa_realtimeStatisticCache(14, 64),
      dsa_realTimeDataStatisticCache(15, 65),
      dsa_terminalStatusCache(16, 66),
      dsa_mmMutualSessionManage(17, 67),
      da_historicalRecordsCache(18, 96),
      ;
      
      public static final int ta_packetHandle_VALUE = 1;
      public static final int ta_messageAddressing_VALUE = 2;
      public static final int ta_messageAnswerTimeout_VALUE = 3;
      public static final int ta_commonCache_VALUE = 4;
      public static final int ta_dataLocalSerialization_VALUE = 5;
      public static final int dp_areaData_VALUE = 32;
      public static final int dp_regularData_VALUE = 33;
      public static final int dp_latestLocationData_VALUE = 34;
      public static final int dp_dictData_VALUE = 35;
      public static final int dp_commonData_VALUE = 36;
      public static final int dp_terminalParameter_VALUE = 37;
      public static final int dp_dpAndTaDataGuarantee_VALUE = 38;
      public static final int dp_messageAddressing_VALUE = 39;
      public static final int dp_encryptData_VALUE = 40;
      public static final int dsa_realtimeStatisticCache_VALUE = 64;
      public static final int dsa_realTimeDataStatisticCache_VALUE = 65;
      public static final int dsa_terminalStatusCache_VALUE = 66;
      public static final int dsa_mmMutualSessionManage_VALUE = 67;
      public static final int da_historicalRecordsCache_VALUE = 96;
      
      
      public final int getNumber() { return value; }
      
      public static CacheType valueOf(int value) {
        switch (value) {
          case 1: return ta_packetHandle;
          case 2: return ta_messageAddressing;
          case 3: return ta_messageAnswerTimeout;
          case 4: return ta_commonCache;
          case 5: return ta_dataLocalSerialization;
          case 32: return dp_areaData;
          case 33: return dp_regularData;
          case 34: return dp_latestLocationData;
          case 35: return dp_dictData;
          case 36: return dp_commonData;
          case 37: return dp_terminalParameter;
          case 38: return dp_dpAndTaDataGuarantee;
          case 39: return dp_messageAddressing;
          case 40: return dp_encryptData;
          case 64: return dsa_realtimeStatisticCache;
          case 65: return dsa_realTimeDataStatisticCache;
          case 66: return dsa_terminalStatusCache;
          case 67: return dsa_mmMutualSessionManage;
          case 96: return da_historicalRecordsCache;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CacheType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CacheType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CacheType>() {
              public CacheType findValueByNumber(int number) {
                return CacheType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MonitorCacheSize.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CacheType[] VALUES = {
        ta_packetHandle, ta_messageAddressing, ta_messageAnswerTimeout, ta_commonCache, ta_dataLocalSerialization, dp_areaData, dp_regularData, dp_latestLocationData, dp_dictData, dp_commonData, dp_terminalParameter, dp_dpAndTaDataGuarantee, dp_messageAddressing, dp_encryptData, dsa_realtimeStatisticCache, dsa_realTimeDataStatisticCache, dsa_terminalStatusCache, dsa_mmMutualSessionManage, da_historicalRecordsCache, 
      };
      
      public static CacheType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CacheType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:MonitorCacheSize.CacheType)
    }
    
    private int bitField0_;
    // required .MonitorCacheSize.CacheType types = 1;
    public static final int TYPES_FIELD_NUMBER = 1;
    private CacheType types_;
    public boolean hasTypes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public CacheType getTypes() {
      return types_;
    }
    
    // required int32 cacheSize = 2;
    public static final int CACHESIZE_FIELD_NUMBER = 2;
    private int cacheSize_;
    public boolean hasCacheSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCacheSize() {
      return cacheSize_;
    }
    
    private void initFields() {
      types_ = CacheType.ta_packetHandle;
      cacheSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTypes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCacheSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, types_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cacheSize_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, types_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cacheSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static MonitorCacheSize parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MonitorCacheSize parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MonitorCacheSize parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MonitorCacheSize parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MonitorCacheSize parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MonitorCacheSize parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MonitorCacheSize parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MonitorCacheSize parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MonitorCacheSize parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MonitorCacheSize parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MonitorCacheSize prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MonitorCacheSizeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LCMonitorCacheSize.internal_static_MonitorCacheSize_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LCMonitorCacheSize.internal_static_MonitorCacheSize_fieldAccessorTable;
      }
      
      // Construct using com.navinfo.opentsp.platform.location.protocol.nodecluster.common.LCMonitorCacheSize.MonitorCacheSize.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        types_ = CacheType.ta_packetHandle;
        bitField0_ = (bitField0_ & ~0x00000001);
        cacheSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MonitorCacheSize.getDescriptor();
      }
      
      public MonitorCacheSize getDefaultInstanceForType() {
        return MonitorCacheSize.getDefaultInstance();
      }
      
      public MonitorCacheSize build() {
        MonitorCacheSize result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private MonitorCacheSize buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        MonitorCacheSize result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public MonitorCacheSize buildPartial() {
        MonitorCacheSize result = new MonitorCacheSize(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.types_ = types_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cacheSize_ = cacheSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MonitorCacheSize) {
          return mergeFrom((MonitorCacheSize)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MonitorCacheSize other) {
        if (other == MonitorCacheSize.getDefaultInstance()) return this;
        if (other.hasTypes()) {
          setTypes(other.getTypes());
        }
        if (other.hasCacheSize()) {
          setCacheSize(other.getCacheSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTypes()) {
          
          return false;
        }
        if (!hasCacheSize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              CacheType value = CacheType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                types_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cacheSize_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MonitorCacheSize.CacheType types = 1;
      private CacheType types_ = CacheType.ta_packetHandle;
      public boolean hasTypes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public CacheType getTypes() {
        return types_;
      }
      public Builder setTypes(CacheType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        types_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        types_ = CacheType.ta_packetHandle;
        onChanged();
        return this;
      }
      
      // required int32 cacheSize = 2;
      private int cacheSize_ ;
      public boolean hasCacheSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCacheSize() {
        return cacheSize_;
      }
      public Builder setCacheSize(int value) {
        bitField0_ |= 0x00000002;
        cacheSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearCacheSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cacheSize_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:MonitorCacheSize)
    }
    
    static {
      defaultInstance = new MonitorCacheSize(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MonitorCacheSize)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitorCacheSize_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MonitorCacheSize_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n9core/proto/nodecluster/common/java/Mon" +
      "itorCacheSize.proto\"\306\004\n\020MonitorCacheSize" +
      "\022*\n\005types\030\001 \002(\0162\033.MonitorCacheSize.Cache" +
      "Type\022\021\n\tcacheSize\030\002 \002(\005\"\362\003\n\tCacheType\022\023\n" +
      "\017ta_packetHandle\020\001\022\030\n\024ta_messageAddressi" +
      "ng\020\002\022\033\n\027ta_messageAnswerTimeout\020\003\022\022\n\016ta_" +
      "commonCache\020\004\022\035\n\031ta_dataLocalSerializati" +
      "on\020\005\022\017\n\013dp_areaData\020 \022\022\n\016dp_regularData\020" +
      "!\022\031\n\025dp_latestLocationData\020\"\022\017\n\013dp_dictD" +
      "ata\020#\022\021\n\rdp_commonData\020$\022\030\n\024dp_terminalP",
      "arameter\020%\022\033\n\027dp_dpAndTaDataGuarantee\020&\022" +
      "\030\n\024dp_messageAddressing\020\'\022\022\n\016dp_encryptD" +
      "ata\020(\022\036\n\032dsa_realtimeStatisticCache\020@\022\"\n" +
      "\036dsa_realTimeDataStatisticCache\020A\022\033\n\027dsa" +
      "_terminalStatusCache\020B\022\035\n\031dsa_mmMutualSe" +
      "ssionManage\020C\022\035\n\031da_historicalRecordsCac" +
      "he\020`BW\nAcom.navinfo.opentsp.platform.loc" +
      "ation.protocol.nodecluster.commonB\022LCMon" +
      "itorCacheSize"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MonitorCacheSize_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MonitorCacheSize_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MonitorCacheSize_descriptor,
              new String[] { "Types", "CacheSize", },
              MonitorCacheSize.class,
              MonitorCacheSize.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
