// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/terminal/monitor/java/MediaDataQuery.proto

package com.navinfo.opentsp.platform.location.protocol.terminal.monitor;

public final class LCMediaDataQuery {
  private LCMediaDataQuery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MediaDataQueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .MediaType types = 1;
    boolean hasTypes();
    com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType getTypes();
    
    // required bool isAllChannels = 2;
    boolean hasIsAllChannels();
    boolean getIsAllChannels();
    
    // optional int32 channels = 3;
    boolean hasChannels();
    int getChannels();
    
    // required .EventCode events = 4;
    boolean hasEvents();
    com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode getEvents();
    
    // required int64 beginDate = 5;
    boolean hasBeginDate();
    long getBeginDate();
    
    // required int64 endDate = 6;
    boolean hasEndDate();
    long getEndDate();
  }
  public static final class MediaDataQuery extends
      com.google.protobuf.GeneratedMessage
      implements MediaDataQueryOrBuilder {
    // Use MediaDataQuery.newBuilder() to construct.
    private MediaDataQuery(Builder builder) {
      super(builder);
    }
    private MediaDataQuery(boolean noInit) {}
    
    private static final MediaDataQuery defaultInstance;
    public static MediaDataQuery getDefaultInstance() {
      return defaultInstance;
    }
    
    public MediaDataQuery getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LCMediaDataQuery.internal_static_MediaDataQuery_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LCMediaDataQuery.internal_static_MediaDataQuery_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .MediaType types = 1;
    public static final int TYPES_FIELD_NUMBER = 1;
    private com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType types_;
    public boolean hasTypes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType getTypes() {
      return types_;
    }
    
    // required bool isAllChannels = 2;
    public static final int ISALLCHANNELS_FIELD_NUMBER = 2;
    private boolean isAllChannels_;
    public boolean hasIsAllChannels() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsAllChannels() {
      return isAllChannels_;
    }
    
    // optional int32 channels = 3;
    public static final int CHANNELS_FIELD_NUMBER = 3;
    private int channels_;
    public boolean hasChannels() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getChannels() {
      return channels_;
    }
    
    // required .EventCode events = 4;
    public static final int EVENTS_FIELD_NUMBER = 4;
    private com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode events_;
    public boolean hasEvents() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode getEvents() {
      return events_;
    }
    
    // required int64 beginDate = 5;
    public static final int BEGINDATE_FIELD_NUMBER = 5;
    private long beginDate_;
    public boolean hasBeginDate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getBeginDate() {
      return beginDate_;
    }
    
    // required int64 endDate = 6;
    public static final int ENDDATE_FIELD_NUMBER = 6;
    private long endDate_;
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getEndDate() {
      return endDate_;
    }
    
    private void initFields() {
      types_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType.picture;
      isAllChannels_ = false;
      channels_ = 0;
      events_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode.platformSend;
      beginDate_ = 0L;
      endDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTypes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsAllChannels()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEvents()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBeginDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, types_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isAllChannels_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, channels_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, events_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, beginDate_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, endDate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, types_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isAllChannels_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, channels_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, events_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, beginDate_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, endDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static MediaDataQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MediaDataQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MediaDataQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static MediaDataQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static MediaDataQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MediaDataQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static MediaDataQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MediaDataQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static MediaDataQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static MediaDataQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MediaDataQuery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MediaDataQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LCMediaDataQuery.internal_static_MediaDataQuery_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LCMediaDataQuery.internal_static_MediaDataQuery_fieldAccessorTable;
      }
      
      // Construct using com.navinfo.opentsp.platform.location.protocol.terminal.monitor.LCMediaDataQuery.MediaDataQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        types_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType.picture;
        bitField0_ = (bitField0_ & ~0x00000001);
        isAllChannels_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        channels_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        events_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode.platformSend;
        bitField0_ = (bitField0_ & ~0x00000008);
        beginDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        endDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MediaDataQuery.getDescriptor();
      }
      
      public MediaDataQuery getDefaultInstanceForType() {
        return MediaDataQuery.getDefaultInstance();
      }
      
      public MediaDataQuery build() {
        MediaDataQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private MediaDataQuery buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        MediaDataQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public MediaDataQuery buildPartial() {
        MediaDataQuery result = new MediaDataQuery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.types_ = types_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isAllChannels_ = isAllChannels_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channels_ = channels_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.events_ = events_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.beginDate_ = beginDate_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.endDate_ = endDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MediaDataQuery) {
          return mergeFrom((MediaDataQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(MediaDataQuery other) {
        if (other == MediaDataQuery.getDefaultInstance()) return this;
        if (other.hasTypes()) {
          setTypes(other.getTypes());
        }
        if (other.hasIsAllChannels()) {
          setIsAllChannels(other.getIsAllChannels());
        }
        if (other.hasChannels()) {
          setChannels(other.getChannels());
        }
        if (other.hasEvents()) {
          setEvents(other.getEvents());
        }
        if (other.hasBeginDate()) {
          setBeginDate(other.getBeginDate());
        }
        if (other.hasEndDate()) {
          setEndDate(other.getEndDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTypes()) {
          
          return false;
        }
        if (!hasIsAllChannels()) {
          
          return false;
        }
        if (!hasEvents()) {
          
          return false;
        }
        if (!hasBeginDate()) {
          
          return false;
        }
        if (!hasEndDate()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType value = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                types_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isAllChannels_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              channels_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode value = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                events_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              beginDate_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              endDate_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .MediaType types = 1;
      private com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType types_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType.picture;
      public boolean hasTypes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType getTypes() {
        return types_;
      }
      public Builder setTypes(com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        types_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        types_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.MediaType.picture;
        onChanged();
        return this;
      }
      
      // required bool isAllChannels = 2;
      private boolean isAllChannels_ ;
      public boolean hasIsAllChannels() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsAllChannels() {
        return isAllChannels_;
      }
      public Builder setIsAllChannels(boolean value) {
        bitField0_ |= 0x00000002;
        isAllChannels_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsAllChannels() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isAllChannels_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 channels = 3;
      private int channels_ ;
      public boolean hasChannels() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getChannels() {
        return channels_;
      }
      public Builder setChannels(int value) {
        bitField0_ |= 0x00000004;
        channels_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannels() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channels_ = 0;
        onChanged();
        return this;
      }
      
      // required .EventCode events = 4;
      private com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode events_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode.platformSend;
      public boolean hasEvents() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode getEvents() {
        return events_;
      }
      public Builder setEvents(com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        events_ = value;
        onChanged();
        return this;
      }
      public Builder clearEvents() {
        bitField0_ = (bitField0_ & ~0x00000008);
        events_ = com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.EventCode.platformSend;
        onChanged();
        return this;
      }
      
      // required int64 beginDate = 5;
      private long beginDate_ ;
      public boolean hasBeginDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getBeginDate() {
        return beginDate_;
      }
      public Builder setBeginDate(long value) {
        bitField0_ |= 0x00000010;
        beginDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearBeginDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        beginDate_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 endDate = 6;
      private long endDate_ ;
      public boolean hasEndDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getEndDate() {
        return endDate_;
      }
      public Builder setEndDate(long value) {
        bitField0_ |= 0x00000020;
        endDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        endDate_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:MediaDataQuery)
    }
    
    static {
      defaultInstance = new MediaDataQuery(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MediaDataQuery)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MediaDataQuery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MediaDataQuery_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n5core/proto/terminal/monitor/java/Media" +
      "DataQuery.proto\032/core/proto/terminal/com" +
      "mon/java/MediaType.proto\032/core/proto/ter" +
      "minal/common/java/EventCode.proto\"\224\001\n\016Me" +
      "diaDataQuery\022\031\n\005types\030\001 \002(\0162\n.MediaType\022" +
      "\025\n\risAllChannels\030\002 \002(\010\022\020\n\010channels\030\003 \001(\005" +
      "\022\032\n\006events\030\004 \002(\0162\n.EventCode\022\021\n\tbeginDat" +
      "e\030\005 \002(\003\022\017\n\007endDate\030\006 \002(\003BS\n?com.navinfo." +
      "opentsp.platform.location.protocol.termi" +
      "nal.monitorB\020LCMediaDataQuery"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MediaDataQuery_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MediaDataQuery_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MediaDataQuery_descriptor,
              new String[] { "Types", "IsAllChannels", "Channels", "Events", "BeginDate", "EndDate", },
              MediaDataQuery.class,
              MediaDataQuery.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.navinfo.opentsp.platform.location.protocol.terminal.common.LCMediaType.getDescriptor(),
          com.navinfo.opentsp.platform.location.protocol.terminal.common.LCEventCode.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
