// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/proto/dataaccess/log/java/TerminalOperateLogUpdate.proto

package com.navinfo.opentsp.platform.location.protocol.dataaccess.log;

public final class LCTerminalOperateLogUpdate {
  private LCTerminalOperateLogUpdate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TerminalOperateLogUpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 terminalId = 1;
    boolean hasTerminalId();
    long getTerminalId();
    
    // required int32 functionCode = 2;
    boolean hasFunctionCode();
    int getFunctionCode();
    
    // required bool results = 3;
    boolean hasResults();
    boolean getResults();
  }
  public static final class TerminalOperateLogUpdate extends
      com.google.protobuf.GeneratedMessage
      implements TerminalOperateLogUpdateOrBuilder {
    // Use TerminalOperateLogUpdate.newBuilder() to construct.
    private TerminalOperateLogUpdate(Builder builder) {
      super(builder);
    }
    private TerminalOperateLogUpdate(boolean noInit) {}
    
    private static final TerminalOperateLogUpdate defaultInstance;
    public static TerminalOperateLogUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public TerminalOperateLogUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.internal_static_TerminalOperateLogUpdate_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.internal_static_TerminalOperateLogUpdate_fieldAccessorTable;
    }

    private int bitField0_;
    // required int64 terminalId = 1;
    public static final int TERMINALID_FIELD_NUMBER = 1;
    private long terminalId_;
    public boolean hasTerminalId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTerminalId() {
      return terminalId_;
    }

    // required int32 functionCode = 2;
    public static final int FUNCTIONCODE_FIELD_NUMBER = 2;
    private int functionCode_;
    public boolean hasFunctionCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getFunctionCode() {
      return functionCode_;
    }

    // required bool results = 3;
    public static final int RESULTS_FIELD_NUMBER = 3;
    private boolean results_;
    public boolean hasResults() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getResults() {
      return results_;
    }

    private void initFields() {
      terminalId_ = 0L;
      functionCode_ = 0;
      results_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTerminalId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunctionCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResults()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, terminalId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, functionCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, results_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, terminalId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, functionCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, results_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.internal_static_TerminalOperateLogUpdate_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.internal_static_TerminalOperateLogUpdate_fieldAccessorTable;
      }

      // Construct using com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        terminalId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        functionCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        results_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate.getDescriptor();
      }

      public com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate getDefaultInstanceForType() {
        return com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate.getDefaultInstance();
      }

      public com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate build() {
        com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate buildPartial() {
        com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate result = new com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.terminalId_ = terminalId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.functionCode_ = functionCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.results_ = results_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate) {
          return mergeFrom((com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate other) {
        if (other == com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate.getDefaultInstance()) return this;
        if (other.hasTerminalId()) {
          setTerminalId(other.getTerminalId());
        }
        if (other.hasFunctionCode()) {
          setFunctionCode(other.getFunctionCode());
        }
        if (other.hasResults()) {
          setResults(other.getResults());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerminalId()) {

          return false;
        }
        if (!hasFunctionCode()) {

          return false;
        }
        if (!hasResults()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              terminalId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              functionCode_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              results_ = input.readBool();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required int64 terminalId = 1;
      private long terminalId_ ;
      public boolean hasTerminalId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTerminalId() {
        return terminalId_;
      }
      public Builder setTerminalId(long value) {
        bitField0_ |= 0x00000001;
        terminalId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTerminalId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        terminalId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 functionCode = 2;
      private int functionCode_ ;
      public boolean hasFunctionCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getFunctionCode() {
        return functionCode_;
      }
      public Builder setFunctionCode(int value) {
        bitField0_ |= 0x00000002;
        functionCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearFunctionCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        functionCode_ = 0;
        onChanged();
        return this;
      }

      // required bool results = 3;
      private boolean results_ ;
      public boolean hasResults() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getResults() {
        return results_;
      }
      public Builder setResults(boolean value) {
        bitField0_ |= 0x00000004;
        results_ = value;
        onChanged();
        return this;
      }
      public Builder clearResults() {
        bitField0_ = (bitField0_ & ~0x00000004);
        results_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TerminalOperateLogUpdate)
    }

    static {
      defaultInstance = new TerminalOperateLogUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TerminalOperateLogUpdate)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TerminalOperateLogUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TerminalOperateLogUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n=core/proto/dataaccess/log/java/Termina" +
      "lOperateLogUpdate.proto\"U\n\030TerminalOpera" +
      "teLogUpdate\022\022\n\nterminalId\030\001 \002(\003\022\024\n\014funct" +
      "ionCode\030\002 \002(\005\022\017\n\007results\030\003 \002(\010B[\n=com.na" +
      "vinfo.opentsp.platform.location.protocol" +
      ".dataaccess.logB\032LCTerminalOperateLogUpd" +
      "ate"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TerminalOperateLogUpdate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TerminalOperateLogUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TerminalOperateLogUpdate_descriptor,
              new String[] { "TerminalId", "FunctionCode", "Results", },
              com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate.class,
              com.navinfo.opentsp.platform.location.protocol.dataaccess.log.LCTerminalOperateLogUpdate.TerminalOperateLogUpdate.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
